name: Basic Workflow

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a Simple Script for Job 1
      run: |
        ls -la
        pwd
        echo "Job 1 Content" > job1.txt

    - name: Upload Artifact for Job 1
      uses: actions/upload-artifact@v2
      with:
        name: job1-artifact
        path: job1.txt

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a Simple Script for Job 2
      run: |
        echo "This is Job 2"
        ls -la
        pwd
        echo "Job 2 Content" > job2.txt

    - name: Upload Artifact for Job 2
      uses: actions/upload-artifact@v2
      with:
        name: job2-artifact
        path: job2.txt

  job3:
    runs-on: ubuntu-latest
    needs: job1

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run a Simple Script for Job 3
      run: |
        echo "This is Job 3"
        ls -la
        pwd
        echo "Job 3 Content" > job3.txt

    - name: Upload Artifact for Job 3
      uses: actions/upload-artifact@v2
      with:
        name: job3-artifact
        path: job3.txt
